### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by maharshi14** [kimmackay/GrapHi-C#1]
Hi, I keep getting these errors for every line of my matrix:

> Use of uninitialized value $sink_chr in numeric eq (==) at generate_adjacency_graph.pl line 193.

> Use of uninitialized value $source_chr in numeric eq (==) at generate_adjacency_graph.pl line 193

> Use of uninitialized value $source_chr in concatenation (.) or string at generate_adjacency_graph.pl line 199.

> Use of uninitialized value $sink_chr in concatenation (.) or string at generate_adjacency_graph.pl line 199.

My matrix does not have a header and column describing the bin numbers and chromosomes as it is in the example file GSM1379427_wt_999a-corrected-matrix_hic.tsv, it only has the interaction values for one chromosome.

I'm using the tool as follows:

`perl generate_adjacency_graph.pl Growing.Rep1_20000_iced_chr21_dense.matrix 2335 1 20000 1 C chr21_cytoscape `

> 2335 = number of lines in my matrix

> 1 = only one chromosome

> 20000 = resolution 

> 1 =  scaling parameter

Could you please help me troubleshoot this? Thanks!

**Comment by kimmackay** [comment]
Hi, thanks for your interest in this tool.

GrapHi-C was not designed for use with single-chromosomes. It relies heavily on the input from both cis- and trans- interactions in order to determine the positioning.

That being said, I did add a second script (generate_adjacency_graph_single_chr.pl) that can be used to generate the adjacency matrices for single chromosomes. This can then be used as input to cytoscape/gephi or a similar tool. When I tested this on my data I got less than optimal results so please use with caution.

All input whole-genome contact maps should have bin and/or chromomsome position labels in the first column and row. The scripts assume this is the case and index appropriately.
